### ISSUE TITLE
binance Faster diff data with real time updates

### ISSUE THREAD

**Issue by mingrui** [lattesir/uxapi#4]
这个可以跟 Okex tbt 对标

![image](https://user-images.githubusercontent.com/699276/76734070-1a7ac000-679d-11ea-91d1-1f2968800554.png)

可以在这里加一下条件：

![image](https://user-images.githubusercontent.com/699276/76734134-3c744280-679d-11ea-847c-4eec8789db5a.png)

如果需要我可以提个 pr

**Comment by lattesir** [comment]
已解决
